### ISSUE TITLE
AWS: Deploy EKS cluster with terraform (vpc and subnets)

### ISSUE THREAD

**Issue by AISlearning** [Annika1712/devops-final-project#15]
Two tasks: one focuses on vpc and subnettting, while the other focuses on permissions and (security groups)
- [ ]  Region eu-central-1
- [ ]  3 Worker Nodes
- [ ]  Type micro
- [ ]  Ingress
- [ ]  Loadbalancer

Use Terraform, AWS CloudFormation, or another IaC tool to define your infrastructure.
Use Kubernetes or Docker Swarm for orchestration to ensure your application can scale horizontally.

**Comment by KhOlga** [comment]
![Image](https://github.com/user-attachments/assets/51f23856-6f06-4851-b27f-afdc104ceb47)

**Comment by KhOlga** [comment]
Here changes for this ticket:
https://github.com/Annika1712/devops-final-project/pull/32

**Comment by KhOlga** [comment]
Hey @Annika1712,

I applied all the changes that you suggested.
You could merge the pull request or approve it.

About comments in main.tf -> I will think about what I can do. But actually, I have already added links to official documentation for all the modules that I used in this code.
