### ISSUE TITLE
Documentation: Create High-level Design of project

### ISSUE THREAD

**Issue by AISlearning** [Annika1712/devops-final-project#27]

**Comment by KhOlga** [comment]
While was looking for info about aws-vpc-eks stuff, have found -> https://www.cloudcraft.co/?utm_source=terraform-aws-vpc

**Comment by KhOlga** [comment]
![Image](https://github.com/user-attachments/assets/c548b789-eb67-4929-a631-b93e2096b0f8)

**Comment by AISlearning** [comment]
https://lucid.app/lucidchart/4e3a6bcb-5008-422b-b667-63366644c4d1/edit?invitationId=inv_36bd019a-f764-471f-9419-90bcca396182&page=0_0#


![Image](https://github.com/user-attachments/assets/578a85bd-3457-43f0-83ac-1cb3e053bde3)
