### ISSUE TITLE
CI/CD: Set up developer branch

### ISSUE THREAD

**Issue by Chi91** [Annika1712/devops-final-project#8]
- [ ] The pipeline should automatically build and test your application.
- [ ]  The CI/CD pipeline should deploy the application without errors.
- [ ] The pipeline should be ready for smooth integration of new code and features.
- [ ]  Adding SonarQube (optional)

**Comment by KhOlga** [comment]
Reviewed.
Working on docker images: build & push.

**Comment by KhOlga** [comment]
Added build & push for Docker images:


![Image](https://github.com/user-attachments/assets/47ffe316-f09a-4a3c-8583-4fad10523e3f)
